# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=70)),
                ('modified_time', models.DateTimeField()),
                ('content', models.CharField(max_length=15000)),
            ],
        ),
    ]
