# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotable',
            name='image',
            field=models.CharField(max_length=70, null=True, verbose_name='image_des'),
        ),
    ]
