# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infotable',
            name='status',
        ),
        migrations.AddField(
            model_name='infotable',
            name='_status',
            field=models.BooleanField(default=0),
        ),
    ]
