# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0002_infotable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotable',
            name='resume',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
