# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0002_auto_20170525_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotable',
            name='latest_chapter',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='infotable',
            name='latest_chapter_url',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
