# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0002_noveltable_need_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=5)),
                ('update_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.AuthorTable')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.CategoryTable')),
            ],
        ),
        migrations.DeleteModel(
            name='NovelTable',
        ),
    ]
