# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0003_auto_20170512_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_boos', to='novel_site.AuthorTable', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate_books', to='novel_site.CategoryTable', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='status',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
