# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 00:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel_site', '0003_auto_20170810_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('update_time', models.DateField(default=datetime.datetime(2017, 8, 28, 0, 15, 51, 816083))),
                ('status', models.CharField(choices=[('0', '连载中'), ('1', '已完结')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fav_books', models.CharField(blank=True, max_length=200)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
