# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0003_auto_20170507_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTableOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('need_confirm', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookTableThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('need_confirm', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookTableTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('need_confirm', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='infotable',
            name='store_des',
            field=models.IntegerField(null=True, verbose_name='book_table_index'),
        ),
        migrations.AddField(
            model_name='booktabletwo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable'),
        ),
        migrations.AddField(
            model_name='booktablethree',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable'),
        ),
        migrations.AddField(
            model_name='booktableone',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable'),
        ),
    ]
