# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0004_formtest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtest',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
