# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0004_auto_20170507_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktableone',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='booktablethree',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='booktabletwo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.AuthorTable', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.CategoryTable', verbose_name='category'),
        ),
    ]
