# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0005_auto_20170828_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileTable',
        ),
    ]
