# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0005_auto_20170507_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='cate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
