# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0012_auto_20170507_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktableone',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='booktablethree',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='booktabletwo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel_site.InfoTable', verbose_name='title'),
        ),
    ]
