# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0013_auto_20170508_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktableone',
            name='chapter',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='booktablethree',
            name='chapter',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='booktabletwo',
            name='chapter',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
