# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel_site', '0014_auto_20170508_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotable',
            name='image',
            field=models.CharField(max_length=70, null=True, verbose_name='image_des'),
        ),
        migrations.AlterField(
            model_name='infotable',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_boos', to='novel_site.AuthorTable', verbose_name='author'),
        ),
    ]
