# Generated by Django 2.0 on 2017-12-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('_status', models.BooleanField(default=0)),
                ('update_time', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=70, null=True, verbose_name='image_des')),
                ('resume', models.CharField(max_length=300, null=True)),
                ('latest_chapter', models.CharField(max_length=70, null=True)),
                ('latest_chapter_url', models.CharField(max_length=70, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='pc.AuthorTable', verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('need_confirm', models.BooleanField(default=0)),
                ('book_name', models.CharField(max_length=70, verbose_name='book_name')),
                ('book_id', models.IntegerField(verbose_name='book_id')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_chapters', to='pc.BookTable', verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='booktable',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_books', to='pc.CategoryTable', verbose_name='category'),
        ),
    ]
