# Generated by Django 2.0 on 2017-12-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='author',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chaptertable',
            name='title',
        ),
        migrations.DeleteModel(
            name='BookTable',
        ),
        migrations.DeleteModel(
            name='ChapterTable',
        ),
    ]
