# Generated by Django 2.0 on 2017-12-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter',
            new_name='ChapterTable',
        ),
    ]
