# Generated by Django 2.0 on 2017-12-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_auto_20171214_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('_status', models.BooleanField(default=0)),
                ('update_time', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=70, null=True, verbose_name='image_des')),
                ('resume', models.CharField(max_length=300, null=True)),
                ('latest_chapter', models.CharField(max_length=70, null=True)),
                ('latest_chapter_url', models.CharField(max_length=70, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='pc.AuthorTable', verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_books', to='pc.CategoryTable', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('need_confirm', models.BooleanField(default=0)),
                ('book_name', models.CharField(max_length=70, verbose_name='book_name')),
                ('book_id', models.IntegerField(verbose_name='book_id')),
                ('next_chapter_id', models.IntegerField(default=0, verbose_name='next_chapter_id')),
                ('prev_chapter_id', models.IntegerField(default=0, verbose_name='prev_chapter_id')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_chapters', to='pc.BookTable', verbose_name='title')),
            ],
        ),
    ]
